version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: painel-licitacoes
    container_name: painel-licitacoes
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped